version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: node_app_image
    ports:
      - 8080:8080
    environment:
      - PG_DB=node_app_image
      - PG_USER=user
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=node_app_image
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}